### ISSUE TITLE
[Feature Request] Auto rotate images

### ISSUE THREAD

**Issue by Nsbld** [nkanaev/bubble#19]
Would it be possible to add an option to auto rotate 90 degrees a wide/tall image?
Currently, single pages fit the screen nicely in portrait mode with the "aspect fit" option selected, but double pages are zoomed out a lot to fit, making them harder to read and wasting a lot of screen space.

**Comment by nkanaev** [comment]
Sorry, I think rotating tablet each time 90 degrees is not such a good idea. However, I might implement the "intelligent" scaling mode. For example, if you are reading in portrait mode, single pages will fit the screen, and the double pages will fill the screen, enabling to move the page horizontally. 

But due to the large fragmentation of android devices, many aspects should be considered too (like reading in landscape mode, screen size etc)
