### ISSUE TITLE
Sort pages by numerical order

### ISSUE THREAD

**Issue by omitter** [nkanaev/bubble#33]
Bubble seems to sort pages in lexicographical order instead of by the number's value. So it sorts pages this way 1 11 12 2 3 4 5 6 7 8 9 when it should be 1 2 3 4 5 6 7 8 9 10 11 12. Unfortunately not all comic books are numbered correctly (001 002 003 004…) for lexicographical sorting to be useful.

**Comment by orangpelupa** [comment]
Yup can confirm this issue

**Comment by wint3** [comment]
Yes. Need a solution. I know why this happens though. Inside the .zip/.cbz file the images are ordered as 1 10 11... 2 20 21 ... so on. In general. Most comic readers I've used reorder this accordingly (i.e 1 2 3...) while we read.
I really like Bubble and would greatly appreciate if it did the same. Please solve this.

**Comment by wint3** [comment]
Yes. Need a solution. I know why this happens though. Inside the .zip/.cbz file the images are ordered as 1 10 11... 2 20 21 ... so on. In general. Most comic readers I've used reorder this accordingly (i.e 1 2 3...) while we read.
I really like Bubble and would greatly appreciate if it did the same. Please solve this.

**Comment by nkanaev** [comment]
thanks for the report. will be fixed in the next release.

**Comment by orangpelupa** [comment]
Can be fixed by replacing the sorting on zip to this 


 Collections.sort(mEntries, new Comparator<ZipEntry>() {
 +            public int compare(ZipEntry a, ZipEntry b) {
 +                return String.format("%100s", a.getName()).compareTo(
 +                        String.format("%100s", b.getName()));
 +            }
 +        });

But the database/library are still sorted incorrectly (that edit will only fix the pages sorting from zip archive)

**Comment by nkanaev** [comment]
fixed. will be part of the next release

**Comment by wint3** [comment]
Great. Will be looking forward to the new update
